rules:
  # YAML GitHub Actions: flag curl | sh patterns
  - id: yaml.github-actions.curl-pipe-sh
    languages: [yaml]
    message: "Avoid piping curl output to shell in CI workflows"
    severity: WARNING
    patterns:
      - pattern-regex: 'curl\s+.*\|\s*(bash|sh)'
    paths:
      include:
        - "/.github/workflows/**"

  # Generic secret patterns in config
  - id: generic.possible-secret
    languages: [generic]
    message: "Possible hardcoded secret detected"
    severity: WARNING
    patterns:
      - pattern-regex: '(?i)(api[_-]?key|token|secret|password)\s*[:=]\s*[^\n]{16,}'
      - pattern-not-regex: '(?i)project-token:\s*\$\{\{\s*secrets\.[A-Z0-9_]+\s*\}\}'
      - pattern-not-regex: '(?i)Read-Host\s+"[^"]*(credential|password|token)[^"]*"\s+-AsSecureString'
      - pattern-not-regex: '(?i)SecureStringToBSTR\(|MakeReadOnly\(\)'
    paths:
      include:
        - "**/*.ps1"
        - "**/*.psd1"
        - "**/*.json"
        - "**/*.yml"
        - "**/*.yaml"
    metadata:
      references:
        - https://semgrep.dev/docs/writing-rules/pattern-syntax/#regex

  # PowerShell: discourage Invoke-Expression on variable input
  - id: powershell.invoke-expression-variable
    languages: [generic]
    message: "Avoid Invoke-Expression with variable input"
    severity: WARNING
    patterns:
      - pattern-regex: '(?i)Invoke-Expression\s+\$[A-Za-z0-9_]+'
    paths:
      include:
        - "**/*.ps1"
        - "**/*.psm1"
